AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create an RDS DB and update

Resources:
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties: 
      DBClusterParameterGroupName: cobpg
      Description: DB Cluster parameter group for cob
      Parameters:
        lower_case_table_names: 1
      Family: aurora-mysql5.7
      Tags: 
        - Key: Name
          Value: COBDBCPG

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      DBParameterGroupName: cobpgg
      Description: DB parameter group for cob
      Parameters:
        sql_mode: 'PIPES_AS_CONCAT'
      Family: aurora-mysql5.7
      Tags: 
        - Key: Name
          Value: COBDBCPGG
  MyPassword:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: masterpwd
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "cobadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@'/'    

  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties: 
      DatabaseName: cobdbrds
      DBClusterParameterGroupName: cobpg
      DBInstanceParameterGroupName: cobpgg
      Engine: aurora-mysql
      MasterUsername: cobadmin
      MasterUserPassword: !Ref MyPassword
  

  DBPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      DBInstanceIdentifier: cobprimary
      DBInstanceClass: db.t3.small
      DBName: cobdb
      DBParameterGroupName: cobpgg
      Engine: aurora-mysql
      Tags:
        - Key: Name
          Value: cobprimary
